name: Run tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y minimap2 samtools bwa spades
          pip install -r requirements.txt

      - name: Run raw_assemble_gene test
        run: bash tests/test_raw_assemble_gene.sh
